{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"downstream\"}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"upstream\"}"
    }
   ]
  },
  {
   "title": "speedtest ping",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    { "expr": "speedtest_ping" }
   ]
  },
  {
   "title": "Downtime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "targets": [
    { "expr": "ip_as_a_number == 0", "legendFormat": " " }
   ]
  },
  {
   "title": "IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    { "expr": "ip_as_a_number" }
   ]
  },
  {
   "title": "speedtest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "speedtest_bits_per_second{}", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "NotAccessible",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "1 - probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}